apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: my-go-app
    newName: mydockerhubusername/my-go-app
    newTag: v1